const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Outfitters',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular Shirt',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Outfitters',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular Shirt',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Outfitters',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular Shirt',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Outfitters',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular Shirt',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Outfitters',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular Shirt',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
  ],
}

export default data
